### PR TITLE
Ehtisham's College Placement Data Analysis

### PR DESCRIPTION
**Pull request by ehtisham-sadiq**
Please review my code

### CODE REVIEW

**Review by AyeshaRashid208 — APPROVED** [review]
approved

**Review by Tayyaba-Nasir — COMMENTED** [review]
Good

**Comment by Tayyaba-Nasir** [comment]
Good

**Review by Tayyaba-Nasir — APPROVED** [review]

**Review by ZainabSaeed2707 — APPROVED** [review]

**Comment by ehtisham-sadiq** [comment]
I completed my project

**Pull request merged**
